### ISSUE TITLE
Training a T5 tokenizer

### ISSUE THREAD

**Issue by ideasbyjin** [agemagician/ProtTrans#119]
Hi, 

I'd like to train a custom protein T5 tokenizer to account for some extra amino acids and tokens, but I'm finding that either:

* Using the existing ProtTrans tokenizer and adding tokens doesn't work with Sentencepiece, OR
* Using Sentencepiece doesn't lead to the same tokenizer that's on the Rostlab pretrained tokenizer set.

Would it be possible to share how you guys trained the tokenizer?

**Comment by mheinzinger** [comment]
Hi,

sorry for the problems - in fact, from what I remember we used plain sentencepiece for training our ProtT5 tokenizer but this remains to be confirmed by @agemagician .
On the side of adding new tokens, I usually just do as described here and that worked well so far: https://www.depends-on-the-definition.com/how-to-add-new-tokens-to-huggingface-transformers/

**Comment by BSharmi** [comment]
I had a question on the tokenizer too,
what would happen if for e.g.g AlbertTokenizer was used instead of T5Tokenizer for fine tuning ProtT5XL?
I recently found https://github.com/vishakhpk/iter-extrapolation/blob/main/aav/train_model_parallel.py have used AlbertTokenizer and I have seen this warning anytime I change the tokenizer
```
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'T5Tokenizer'. 
The class this function is called from is 'AlbertTokenizer'.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
```

So was curious to know what did you all think of changing the tokenizer?

**Comment by mheinzinger** [comment]
I would absolutely not change the tokenizer. This will most likely result in downstream problems due to non-sense embeddings.
The problem is that you absolutely need to stick to the tokenization schema the model was trained on, e.g. "A" always has to map to e.g. "3"; if you change this mapping in any way, you essentially change the protein sequence passed to the model.
I would also not see any reason to do this, tbh

**Comment by ideasbyjin** [comment]
Yeah, I was asking more to maybe add tokens to an existing tokenizer but
I'd never swap tokenizers out for incompatible models. That effectively
destroys your embedding lookups

**Comment by mheinzinger** [comment]
Absolutely. My answer was only referring to @BSharmi .
You should be good2go with adding new tokens to the T5Tokenizer using the link I put above (that worked well for me)
