### ISSUE TITLE
Sequence extraction from embedding representation

### ISSUE THREAD

**Issue by IliasGewr** [agemagician/ProtTrans#129]
First of all i would like to express my appreciation for your work.

So i would like to know if there is a way from a protein sequence embedding  generated by a protT5 model, to get back the origin protein sequence.

If yes how should this be implemented?

Thank you.

**Comment by mheinzinger** [comment]
I assume you are referring to embeddings from the Encoder-side of ProtT5? - 
If yes, I think there are two ways:
- Train your own predictor on top of the encoder embeddings (really just a simple linear layer put on top of the Encoder embeddings). In order to avoid that the model just copy&pastes information from the input to the output, I would always pick a single residue in a sequence, mask it (use "<extra_id_0> - better check how the token is called exactly"), and then ask the linear head to reconstruct it. You can just iterate over e.g. a nonredundant version of SwissProt, mask one residue at a time, reconstruct it and then move on to the next protein.
- Try the following (this should leverage the already pre-trained ProtT5 decoder to generate you a protein sequence from encoder embeddings): https://huggingface.co/docs/transformers/model_doc/t5#transformers.T5Model.forward.decoder_inputs_embeds
