### ISSUE TITLE
Replicating a basic Protrans model

### ISSUE THREAD

**Issue by donal1** [agemagician/ProtTrans#13]
Hi Rostlab, 

As the title says I'm trying to replicate the bert transformer model in the ProTrans paper on the huggingface platform. I have a few questions regarding the preprocessing steps. Please get back to me when you get a chance. 

Best 

Donal Naylor

**Comment by agemagician** [comment]
Hi Donal,

We haven't use huggingface for training our models. We have used the official training scripts for each model, here is the list of the training source code for each model:

- Bert: https://github.com/google-research/bert
- Albert: https://github.com/google-research/albert
- Electra: https://github.com/google-research/electra
- T5: https://github.com/google-research/text-to-text-transfer-transformer
- XLNet: https://github.com/zihangdai/xlnet
- Transformer XL: https://github.com/cybertronai/transformer-xl

We only used huggingface for inference, so I can't help you regarding what kind of specific processing steps that you should perform for huggingface library.

However, the general preprocessing steps were explained on the paper in section "2.1 Data for Language Models (LMs)", which is same as NLP:
`Both UniRef100 and BFD were tokenized with a single space (indicating word-boundaries) between each token. Each protein sequence was stored on a separate line, with lines/proteins representing the equivalent of “sentences”. Additionally, an empty line was inserted between each protein sequence in order to indicate the “end of a document” as some LMs such as Bert use consecutive sequences for an auxiliary task, i.e. next-sentence prediction, which was not used in this work.`

The only minor filtering step was also mentioned on the paper on section "2.1 Data for Language Models (LMs)":
`As a minor filtering step, all non-generic or unresolved amino acids (B, O, U, Z) were mapped to ‘unknown’ (X).`

**Comment by donal1** [comment]
Thanks for this

**Comment by TonyTang1997** [comment]
Hi Rostlab,

May I know which tokenizer are you using for training? I have tried to used the WordLevel tokenizers by huggingface but not successful. Any possibility that you can opensource the tokenizer also? Thanks!

**Comment by agemagician** [comment]
We have not used hugging-face tokenizer. We have used each model's original tokenizer:

- Bert: https://github.com/google-research/bert
- Albert: https://github.com/google-research/albert
- Electra: https://github.com/google-research/electra
- T5: https://github.com/google-research/text-to-text-transfer-transformer
- XLNet: https://github.com/zihangdai/xlnet
- Transformer XL: https://github.com/cybertronai/transformer-xl
