### ISSUE TITLE
Predicting the properties of bacteria

### ISSUE THREAD

**Issue by slgero** [agemagician/ProtTrans#17]
Thank you for such a great job, it was interesting to read your article, it is amazing!🚀

At the moment, my task is to predict the properties of a bacterium (ph level, oxygen condition, etc.) by the composition of its proteins. Because the amount of proteins is huge, I'm afraid BERT is not suitable for this task. Could you tell me if there are any other solutions that will help me solve this problem?

**Comment by agemagician** [comment]
What I understood from you that your problem is inference speed, which will be slow because you have huge amount of proteins.

Generally, ProtBert-BFD is much faster than the fastest alignment method to date.

You can increase the inference speed/throughput using three methods:

1. GPU:
1.1 Use a faster GPU like Nvidia V100.
1.2. Use multiple GPUs.

2. Model Optimization:
2.1 Use FP16 rather than FP32 : https://discuss.pytorch.org/t/inference-with-halftensor-for-speed-up/5739
2.2. Use Onnx (Beta): https://github.com/agemagician/ProtTrans/blob/master/Embedding/Onnx/ProtBert-BFD.ipynb
2.3. Use Quantization: https://pytorch.org/docs/stable/quantization.html

3. Training Optimization:
3.1 Retrain the model using distillation and pruning: https://arxiv.org/abs/2010.13382

**Comment by sacdallago** [comment]
@slgero you can split up the dataset in multiple FASTA chunks and embedd piece-by-piece? Is that an option? ;) also, feel like you might want to check out our computational biology friendly wrapper around some prottrans models: https://github.com/sacdallago/bio_embeddings

**Comment by slgero** [comment]
@sacdallago Thanks for your reply, I have already tried using your library for several months. It is certainly gorgeous, but unfortunately it did not fit my task 😒

**Comment by sacdallago** [comment]
Sad! :cry: anything I should know to make it more useful? :)
