### ISSUE TITLE
Is batch inference helpful for performance?

### ISSUE THREAD

**Issue by yzhang-github-pub** [agemagician/ProtTrans#32]
Dear Author,

For ProtBert subloc classification, your code is for prediction of one input sequence at a time. If input sequence file is huge, speed becomes a critical issue. What is your advice on performance improvement? I am thinking using GPU and batch inferences. Very likely you have already tested these things. I'd appreciate if you share your insight. Thanks.

**Comment by agemagician** [comment]
You can increase inference throughput by using the following methods:
1. Use GPU rather than CPU.
2. Use batch processing rather than a single sequence per batch.
3. Order your sequence according to length and perform dynamic batching (high batch size for short sequences and lower batch size for longer sequences).
4. Use half-precision (i.e: model.half() )
5. Try quantization (https://pytorch.org/docs/stable/quantization.html)
6. Use Onnx rather than PyTorch for inference.

**Comment by yzhang-github-pub** [comment]
Thanks a lot!
