### ISSUE TITLE
Should I always convert the rarely occured amino acid token (B O U Z)?

### ISSUE THREAD

**Issue by wangwwno1** [agemagician/ProtTrans#41]
Hello, I'm using the pre-trained model as a feature extractor for classification task.
My input peptide sequence contains some rare amino acids(e.g. B O). Since these peptide is much shorter than common proteins I would like to preserve these rare tokens instead to treat them as unk/any amino acid(X).

Here is my question:
- Can I directly feed the inputs to the pre-train model without using the X token?
- If not, which parameter should I retrain?

**Comment by mheinzinger** [comment]
Hey,
yes, you can directly feed the inputs to the pre-trained model without using the unknown (X) token.
However,  I would be surprised if this would improve performance because while we included those tokens in the vocabulary we replaced them during pre-training, i.e., the model never saw those tokens during pre-training and thus most likely also did not learn a reasonable representation for those.
I would recommend to simply test how far you get with replacing them with "X".
Re-training the whole model to learn reasonable representation for those rare tokens would be extremely complicated as you would need a large set of sequences that contain enough of those rare tokens to learn useful representations.
I hope this helps; Michael
