### ISSUE TITLE
Please help with fine tuning of T5 model

### ISSUE THREAD

**Issue by yzhang-github-pub** [agemagician/ProtTrans#51]
Dear authors,

Thanks for your excellent work, the pretrained models are very useful to my projects. For example, I fine tuned protbert-bfd model based on your sample code on subloc classification, and got very good results. Now T5 model outperforms bert model. Can you publish T5 fine tuning code? Thanks a lot!

**Comment by agemagician** [comment]
Thanks for your interest.

Our publication results were only focused on feature extraction rather than fine-tuning.

We provided two fine-tune examples for the purpose of showing the possibility of fine-tuning our models. However, we are not planning to provide fine-tuning examples for all models.

We will be happy if you build an example for the T5 model and send us a pull request.
We always welcome community contribution.
