### ISSUE TITLE
Generating embeddings in batches

### ISSUE THREAD

**Issue by Xinxinatg** [agemagician/ProtTrans#54]
Thanks for this magnificent work! Just wondering are there released code to generate sequence embeddings in batches. Like the one in ESM model (https://github.com/facebookresearch/esm/blob/master/extract.py). I found it took ages to extract embeddings one by one especially for sequences of length longer than ~6000.

**Comment by agemagician** [comment]
Hello,

All the examples in this folder are generating embedding in batches:
https://github.com/agemagician/ProtTrans/tree/master/Embedding/PyTorch/Advanced

You need to replicate the code, and it will process it in batches.
Also, make sure you are using the GPU for generating the embedding.
Finally, long sequences usually take more time than short sequences due to the nature of the transformers' models.
