### ISSUE TITLE
protein sequence embedding for t-sne

### ISSUE THREAD

**Issue by ddongminstar** [agemagician/ProtTrans#65]
Thanks for your excellent jobs for works.

I want to visualize set of protein sequences with t-SNE like fig 3B 

As I can see, result of features are size (num_sequence, length of sequence, 1024).
In, #27 input examples are just one amino acids. 
I want to make it vectors with fixed size of 1024 to pass them to t-SNE. 

Can I take sum or get average of 1024 dimensional vectors for each sequence?
Or just take last result of hidden state for result of embedding vectors for each sequence?

I am just wondering is it feasible to use same approach like #27 (cosine distance and other parameters for t-SNE).

Would you like to share source code for drawing fig 3B? 
Thank you for your great job again.

**Comment by mheinzinger** [comment]
You are perfectly right: you first need to squeeze variable-sized protein sequence embeddings into fixed-length vectors, irrespective of the protein's length. We usually averaged over the "length of sequence" dimension in your example above (resulting in a vector of size num_sequence x 1024) because averaging takes into account that you summed over a variable number of residues. Though, summing should also work but might be biased towards sequence lengths.
That being said: my code for generating Fig 3B and so forth is very similar to the code in the example linked above. However, I would have to clean & comment the code for Fig. 3B first which would only happen by mid January. So I would recommend that you simply see how far you get with averaging plus the code in your linked example and if this does not work, feel free to re-open.
