### ISSUE TITLE
Language modeling heads

### ISSUE THREAD

**Issue by jaekor91** [agemagician/ProtTrans#7]
Thank you for making available these models. Could you also share language modeling classification task heads, e.g., for BERT models?

**Comment by agemagician** [comment]
Hi @jaekor91 ,

On the [Fine Tuning](https://github.com/agemagician/ProtTrans/tree/master/Fine-Tuning) section, you will find examples for fine-tuning ProtBert model for different task.

You simply need to run it on Google Colab, then you can download the model.

Is this what you are looking for?

**Comment by agemagician** [comment]
I have also started to add new model heads for classification tasks:
https://github.com/agemagician/ProtTrans/blob/master/Prediction/ProtBert_BFD_Predict_MS.ipynb

I will close this issue and feel free to open it if the above comments didn't answer your question.

**Comment by jaekor91** [comment]
Sorry for the late reply. I was referring to amino acid classification head that is used to turn contextual embeddings into probs over AAs.

**Comment by agemagician** [comment]
Our models support all huggingface model heads, if what you are looking there, then it is supported, otherwise, not.
You can find the list of heads for each model in huggingface website, for example, this is a list of all Bert heads which is supported:
https://huggingface.co/transformers/model_doc/bert.html#
