### ISSUE TITLE
U class in "membrane" vs. "water soluble" dataset

### ISSUE THREAD

**Issue by ratthachat** [agemagician/ProtTrans#73]
Hi, I have a question regarding the "membrane" vs. "water soluble" dataset, do you think is there some reasoning not to disregard the U class ?

**Comment by mheinzinger** [comment]
Hi,
if you only want to train on membrane vs water-soluble, I do not see a reason to discard the Unknow/U.
We only kept it because we wanted to use the exact same dataset as the original authors of this dataset: https://services.healthtech.dtu.dk/service.php?DeepLoc-1.0
Also it made multi-task learning of subcellular localization and membrane/soluble easier.
But no reason to exclude them if you are not interested in either of those things.
