### ISSUE TITLE
Do we have pre-computed embeddings of known protein sequences available for download? 

### ISSUE THREAD

**Issue by johnnytam100** [agemagician/ProtTrans#80]
I am trying to prepare the ProtTrans embeddings for UniRef50.
Do we have such pre-computed embeddings available for download?
Thanks!

**Comment by mheinzinger** [comment]
For per-residue embeddings I think that this will blow the disk-space for most people and if you only allow bulk download instead of accessing single/few sequences, downloading might in fact take longer than creating them locally.
But this depends, of course, heavily on your available connection/infrastructure and use-case.
Per-Protein embeddings would definitely work; we had created them last year but did not see a specific use-case. I could check whether we still have them lying around if that helps?
What we provide is pre-computed embeddings/predictions for human: https://zenodo.org/record/5047020#.YgZq08CvDDs

**Comment by johnnytam100** [comment]
Hi Heinzinger! Thanks for your prompt reply and the link for human protein embeddings! 
Do you mean you may still have the per-protein embeddings for UniRef50 or something like that?
It will be extremely helpful if you still have it.

**Comment by mheinzinger** [comment]
I've checked and what we had was only UniRef50 for SeqVec not ProtTrans. So I am afraid that you will have to compute those on your end. I would actually recommend to only run ProtT5-XL-U50 as it was shown to perform best on all tasks we've evaluated so far compared to the other ProtTrans models.
If you have UniRef50 as download and would be be willing to share it, I could put it a link to this github so that others can also access it.

**Comment by johnnytam100** [comment]
Currently, I am using [bio_embeddings](https://github.com/sacdallago/bio_embeddings) to extract embeddings from ProtTrans model, which is quite slow so my gut feeling to scaling the extraction to the size of UniRef50 should be difficult... (but will try to see how to push the speed as much as possible). I have just taken a look at the performance of SeqVec vs ProtT5-XL-U50 and dare to give it a try meanwhile because pre-computed embeddings are available! Is it possible to download the SeqVec per-protein embeddings for UniRef50?

**Comment by johnnytam100** [comment]
Luckily, I found this -> http://sigmat.ugr.es/~amelia/FoldEmbeddings/
I will first download the embeddings to see how the data goes! :)

**Comment by mheinzinger** [comment]
In fact, I also realized some slow-down when switching from my own [script](https://colab.research.google.com/drive/1TUj-ayG3WO52n5N50S7KH9vtt6zRkdmj?usp=sharing) to the [bio_embeddings implementation](https://github.com/sacdallago/bio_embeddings/blob/develop/bio_embeddings/embed/prottrans_t5_embedder.py#L123). I could imagine that this is due to bio_embeddings first moving per_residue embeddings to CPU and computing the mean there, instead of simply computing everything on the GPU and only move the per_protein embeddings to CPU.
If you could confirm/reject this, this would be extremely helpful and we are always happy about pull-requests for bio_embeddings.
As a faster solution, you could also the colab-script linked above.

**Comment by johnnytam100** [comment]
Hi @mheinzinger !
Eventually I want to compute ProTrans embeddings for UniRef90 and I have tried your script to estimate the computation time required: which is >1.5 year on my hardwares... 

May I know if you have the computational resources to compute the ProtTrans embeddings for the whole UniRef90 within reasonable computation time? 

In return, we offer you as a co-author of our manuscript , that studies the protein sequence space, at the time of publication. How do you think?

**Comment by XinshaoAmosWang** [comment]
@johnnytam100 , probably I can help you with the computational resources and parallel computing to speed up. 
Look forward to chatting with you.

**Comment by mheinzinger** [comment]
Thanks for jumping in @johnnytam100 ! - In fact, our computing resources are currently also mostly eaten up by a few new projects which is why I would also have problem to provide you embeddings for UniRef90 soon'ish.
If you want to share your embeddings at one point, I would be happy to link to it from our ProtTrans repo :)

**Comment by johnnytam100** [comment]
> @johnnytam100 , probably I can help you with the computational resources and parallel computing to speed up. Look forward to chatting with you.

Hi Wang, thanks for your offer! Would you mind leaving me your email address so I can reach you? 


> Thanks for jumping in @johnnytam100 ! - In fact, our computing resources are currently also mostly eaten up by a few new projects which is why I would also have problem to provide you embeddings for UniRef90 soon'ish. If you want to share your embeddings at one point, I would be happy to link to it from our ProtTrans repo :)

I see and never mind! I hope I can have the UniRef90 embeddings soon!

**Comment by mheinzinger** [comment]
In case you want to generate embeddings on a large scale just a minor tip (maybe obvious, in this case simply ignore):
- For convenience you can use the ProtT5 encoder model that we've added to huggingface right away: https://huggingface.co/Rostlab/prot_t5_xl_half_uniref50-enc
- Explicitly cast this model to half-precision via `model=model.half()` to ensure that the model is run in fp16 (if you do not enforce this explicitly, the model will be run in full-precision from what I saw)
- Batch processing will buy you a few percentages in speed-up but half-precision is much more important

**Comment by xinshao-wang** [comment]
> 

Hi @johnnytam100 , my email address is xinshaowang@gmail.com. Thanks.

**Comment by XinshaoAmosWang** [comment]
> > @johnnytam100 , probably I can help you with the computational resources and parallel computing to speed up. Look forward to chatting with you.
> 
> Hi Wang, thanks for your offer! Would you mind leaving me your email address so I can reach you?
> 
> > Thanks for jumping in @johnnytam100 ! - In fact, our computing resources are currently also mostly eaten up by a few new projects which is why I would also have problem to provide you embeddings for UniRef90 soon'ish. If you want to share your embeddings at one point, I would be happy to link to it from our ProtTrans repo :)
> 
> I see and never mind! I hope I can have the UniRef90 embeddings soon!

Hi @johnnytam100 , my personal email is `xinshaowang@gmail.com`. I look forward to your message.

**Comment by SalvatoreRa** [comment]
Hi, 

I would like to know if you have the precomputed embedding for the human proteins. I am just interested in the vectors for the all human proteins (for example TP53 and the corresponding vector). I want to use the vectors for some classification models using the embedding vectors as additional features. 

thank you for your help

**Comment by mheinzinger** [comment]
Hi,
you can download pre-computed ProtT5 embeddings for human here:
https://zenodo.org/record/5047020
By now, there is also an integration of ProtT5 embeddings in UniProt which allows you to download pre-computed embeddings for a subset of organisms here:
https://www.uniprot.org/help/embeddings
