### ISSUE TITLE
Positional Encoding in ProtBERT

### ISSUE THREAD

**Issue by balvisio** [agemagician/ProtTrans#84]
Hi all,

I have two questions related to the positional encoding in ProtBERT:
- The ProtTrans paper states that models such as BERT "can process only sequences shorter or equal to the length of the positional encoding which has to be set before training." IIUC, BERT actually uses a positional embedding layer (i.e. a learned positional encoding), not the sinusoidal positional encoding used in the paper "Attention is all you need". Maybe, this is just a nomenclature issue. Is ProtBERT slightly tweaked from the BERT paper and uses a sinusoidal positional encoding or does it use a positional embedding (i.e. learnable positional encoding)? Any clarification would be greatly appreciated.

Note: I compared the weights in the embedding layers of ProtBert and ProtBert BFD but the weights of the embedding layer are different from which I suspect it is a positional embedding layer.

- Related to the previous question: the paper mentions that ProtBERT was trained in sequences of length < 512 and < 2048. Given that the final positional encoding is of length 40K, was any training done on sequences of approximately that length? Wondering if you considered it unnecessary.

Thank you!

**Comment by mheinzinger** [comment]
On the positional encoding: we used the official TensorFlow-Implementation of BERT and did not change it.
My understanding was/is that BERT has no learnt positional encoding and that such things were only introduced later by e.g. T5.
Instead, if I'm not mistaken, BERT only relied on "fixed" sinusoidal positional information that simply gets summed to the input.
From a practical perspective, you CAN process sequences longer than the maximum sequence length that we trained on but performance might go down if your sequence length is much longer than what we've trained on (e.g. if you try to embed a protein with 5k residues, ProtBERT's fixed positional encoding could not extrapolate well from the range it was trained on).

On your note: not sure which layer you exactly extracted but if you refer to the actual "embedding" layer in BERT: this will only encode your tokens without any context. For ProtBERT, this gives you the uncontextualized vectors of each amino acid (20 vectors a 1024-d). The positional encoding only gets summed afterwards.

On the L=40k: no, we never trained on anything beyond 2k due to the exponential memory consumption. We only set it to 40k to still allow users to generate embeddings for proteins that are longer than what we trained on. In our hands, ProtBERT extrapolated to a certain degree, still giving reasonable predictions for proteins longer than 2k. But if you talk about really long proteins, e.g. >10k, the number of labeled proteins that we could use to cross-check shrinks to such an extent that we could not evaluate whether this is still useful.

In general, I would not use ProtBERT. Simply use ProtT5 which uses a learnt positional encoding which was shown in NLP to extrapolate much better than (Prot)BERT to longer sequences.

**Comment by balvisio** [comment]
Thank you @mheinzinger for the reply. I did a bit more research and I am pretty confident that:
- The original "Attention is all you need" paper is the one that uses the fixed sinusoidal positional encoding (not BERT)
- BERT uses learned positional embedding instead (no fixed function). The author mention positional embeddings in their paper. Also in the implementation of BERT in the HuggingFace transformer library we can see the "position" EmbeddingLayer as part of the complete "BERT Input embedding" layer:

https://github.com/huggingface/transformers/blob/main/src/transformers/models/bert/modeling_tf_bert.py#:~:text=with%20tf.name_scope(%22position_embeddings%22)%3A

Thank for your other comments, really helpful; Yes, I guess computing self attention for large sequences requires a lot of memory resources.

**Comment by balvisio** [comment]
Thank you for all the help!
